import Foundation

enum Lang: String, CaseIterable, Codable { case ru, en }

// Live-switchable localization (the in-app language toggle must apply instantly,
// which String Catalogs can't do). Copy is ported verbatim from the VeloQuest
// handoff, with extra keys the screens need. `s(key)` returns the raw key if
// missing (visible in the UI, easy to catch).
struct Loc {
    let lang: Lang
    func s(_ key: String) -> String { (lang == .ru ? Loc.ru : Loc.en)[key] ?? key }
    func kind(_ k: String) -> String { s("kind_" + k) }
    func surf(_ k: String) -> String { s("surf_" + k) }
    func poiKind(_ k: String) -> String { s("poi_" + k) }
    func cat(_ k: String) -> String { s("cat_" + k) }
    func reason(_ r: String) -> String { s("reason_" + r) }

    static let ru: [String: String] = [
        "skip": "Пропустить", "next": "Далее", "start": "Поехали", "done": "Готово", "cancel": "Отмена", "back": "Назад",
        "ob1t": "Вся веломосква на одной карте", "ob1d": "Защищённые дорожки, полосы и MTB-тропы — с типом покрытия и свежестью данных.",
        "ob2t": "Маршрут от А до Б для велосипеда", "ob2d": "Профили «Город» и «MTB», набор высоты и доля пути по инфраструктуре.",
        "ob3t": "Держим карту свежей вместе", "ob3d": "Сообщайте о проблемах и добавляйте дорожки — получайте баллы за принятый вклад.",
        "signSub": "Карта велоинфраструктуры Москвы, свежая благодаря сообществу", "signApple": "Войти через Apple", "signGoogle": "Войти через Google",
        "signNote": "Вход обязателен. Мы храним только идентификатор входа, никнейм и ваш вклад.",
        "guestEnter": "Войти без авторизации",
        "editProfile": "Изменить профиль", "save": "Сохранить", "nickname": "Никнейм",
        "editSegment": "Изменить", "segRemoved": "Больше не существует", "editSuccess": "Отправлено на модерацию",
        "searchPh": "Поиск места или адреса",
        "actionTitle": "Что добавить на карту?",
        "aReport": "Сообщить о проблеме", "aDraw": "Предложить дорожку", "aPoi": "Добавить точку (POI)",
        "tMap": "Карта", "tRoute": "Маршрут", "tContrib": "Мой вклад", "tProfile": "Профиль", "tHome": "Домой", "tQuests": "Лига",
        "kind_prot": "Защищённая дорожка", "kind_lane": "Полоса на дороге", "kind_shared": "Пешеходно-велодорожка", "kind_mtb": "MTB-тропа", "kind_other": "Веломаршрут",
        "surf_asphalt": "Асфальт", "surf_ground": "Грунт", "surf_gravel": "Гравий", "surf_unknown": "Неизвестно",
        "poi_workshop": "Веломастерская", "poi_parking": "Велопарковка", "poi_rental": "Прокат велосипедов", "poi_fountain": "Питьевой фонтанчик",
        "cat_pothole": "Яма на дороге", "cat_glass": "Стекло / мусор", "cat_closure": "Перекрытие", "cat_hazard": "Опасность", "cat_other": "Другое",
        "surface": "Покрытие", "quality": "Состояние", "source": "Источник", "updated": "Обновлено",
        "srcOsm": "OpenStreetMap", "srcCom": "Данные сообщества", "good": "Хорошее", "reportHere": "Сообщить о проблеме",
        "address": "Адрес", "routeHere": "Маршрут сюда",
        "confirm": "Подтвердить", "gone": "Уже нет", "confN": "подтверждений",
        "layersTitle": "Слои карты", "legend": "Типы инфраструктуры", "lInfra": "Велоинфраструктура", "lMtb": "MTB-тропы", "lPoi": "Полезные места", "lReports": "Сообщения",
        "searchTitle": "Поиск", "recent": "Недавнее",
        "routeTitle": "Маршрут", "from": "Откуда", "to": "Куда", "myLoc": "Моё местоположение", "pickOnMap": "Указать на карте",
        "profCity": "Город", "profMtb": "MTB", "build": "Построить маршрут", "rebuild": "Изменить", "dist": "Расстояние", "timeL": "В пути", "ascent": "Набор",
        "onInfra": "по велоинфраструктуре", "elevation": "Профиль высоты", "saveRoute": "Сохранить в избранное", "savedRoute": "Маршрут сохранён",
        "routeHintTitle": "Куда едем?", "routeHintDesc": "Укажите точку на карте, найдите адрес или начните от своей геопозиции.",
        "contribTitle": "Мой вклад", "lvl": "Уровень", "toNext": "до уровня", "xpEdits": "правки", "xpReports": "сообщения", "xpConf": "подтверждения",
        "history": "История начислений", "rankTop": "Топ 3% райдеров района",
        "today": "сегодня", "yst": "вчера",
        "profileTitle": "Профиль", "favorites": "Избранное", "myReports": "Мои сообщения", "myEdits": "Мои правки", "ridesItem": "Поездки", "settingsItem": "Настройки", "pts": "баллов",
        "ridesTitle": "Поездки", "healthTitle": "Импорт из Apple Health", "healthWhy": "Читаем велотренировки, чтобы показать трек, скорость и пульс. Данные остаются только на вашем устройстве и не отправляются на сервер.", "healthConnect": "Разрешить доступ к Health", "healthPriv": "Только чтение · Локально",
        "importSel": "Импортировать", "avgSpeed": "Средняя", "maxSpeed": "Макс.", "durationL": "Время", "heartL": "Ср. пульс", "localOnly": "Хранится только на устройстве",
        "ridesEmpty": "Велотренировок не найдено", "ridesEmptyHint": "Запишите заезд в приложении здоровья или на часах — он появится здесь.", "healthUnavailable": "Apple Health недоступен в этой среде",
        "settingsTitle": "Настройки", "language": "Язык", "theme": "Оформление", "themeLight": "Светлое", "themeDark": "Тёмное", "themeSystem": "Системное", "about": "О приложении", "privacyItem": "Политика конфиденциальности", "rulesItem": "Правила сообщества", "deleteAcc": "Удалить аккаунт", "versionL": "Версия", "deleteWarn": "Правки и сообщения останутся на карте, но будут отвязаны от вас.", "deleteConfirm": "Удалить аккаунт?",
        "repTitle": "Проблема на карте", "chooseCat": "Что случилось?", "commentL": "Комментарий", "commentPh": "Опишите подробнее (необязательно)", "photosL": "Фото · до 3", "locationL": "Место — по вашей геопозиции", "submit": "Отправить", "repSuccess": "Спасибо! +10 баллов после модерации",
        "drawTitle": "Новая дорожка", "drawHint": "Нажимайте на карту, чтобы поставить точки линии", "drawHint2": "Перетаскивайте точки, чтобы уточнить", "ptsN": "точек", "undo": "Отменить", "clearL": "Очистить", "drawNext": "Далее", "drawBack": "Назад", "drawKindL": "Тип дорожки", "drawSurfaceL": "Покрытие", "drawPhotoL": "Фото (необязательно)", "drawSubmit": "На модерацию", "drawSuccess": "Дорожка отправлена! +50 баллов после проверки", "reviewNote": "Появится на карте как «данные сообщества» после проверки",
        "poiAddTitle": "Новая точка", "poiNameL": "Название", "poiNamePh": "Например, «Веломастерская»", "poiTypeL": "Тип точки", "poiSuccess": "Точка отправлена! +20 баллов после проверки",
        "hubHi": "Привет", "hubSub": "Сделаем город удобнее для велосипеда?",
        "xpTo": "XP до ур.", "streak": "дней подряд", "streakLabel": "Серия", "streakRecord": "рекорд",
        "dailyQuests": "Задания дня", "questRefresh": "обновятся через 6 ч",
        "badgesL": "Значки", "leaderboard": "Рейтинг района", "you": "Вы", "viewAll": "Всё",
        "qaReport": "Репорт", "qaLane": "Дорожка",
        "lvlUp": "Уровень повышен!", "levelUpOverline": "УРОВЕНЬ ПОВЫШЕН!", "claim": "Забрать", "questReady": "Готово к получению", "newBadge": "Новый значок",
        "locked": "Скоро", "earnedL": "Получен", "progressL": "Прогресс",
        "leagueTitle": "Лига", "leaguePromo": "ЗОНА ПОВЫШЕНИЯ", "leagueDemo": "Ниже — зона вылета", "leaguePromoNote": "Топ 5 проходят в следующую лигу", "seasonTier": "Тир", "daysShort": "дн.", "timeLeft": "осталось",
        "reason_edit_approved": "Правка принята", "reason_poi_approved": "Точка принята", "reason_report_validated": "Сообщение подтверждено", "reason_confirm": "Подтверждение репорта", "reason_quest": "Награда за задание",
        "conquerNote": "3 дорожки до захвата района", "districtData": "Данные района", "districtFresh": "обновлены 2 дня назад",
        "osmAttribution": "© Участники OpenStreetMap", "odblNote": "Картографические данные © OpenStreetMap, лицензия ODbL.", "routesAdvisory": "Маршруты носят рекомендательный характер. Оценивайте обстановку на дороге самостоятельно.", "aboutTagline": "Свежая карта велоинфраструктуры, которую держит в тонусе сообщество.",
        "rulesTitle": "Правила сообщества", "rule1t": "Проверяйте на месте", "rule1d": "Добавляйте дорожки и точки, в которых уверены — лучше по факту, а не по памяти.", "rule2t": "Уважайте приватность", "rule2d": "Не создавайте сообщения прямо у своего дома, если не хотите раскрывать локацию.", "rule3t": "Будьте точны", "rule3d": "Точные тип и покрытие помогают другим планировать безопасный маршрут.", "rule4t": "Без спама", "rule4d": "Дубли и ложные правки отклоняются модерацией, баллы за них не начисляются.",
        "loading": "Загрузка…", "retry": "Повторить", "netError": "Не удалось загрузить. Проверьте сеть.",
    ]

    static let en: [String: String] = [
        "skip": "Skip", "next": "Next", "start": "Let's ride", "done": "Done", "cancel": "Cancel", "back": "Back",
        "ob1t": "All of cycling Moscow on one map", "ob1d": "Protected paths, lanes and MTB trails — with surface type and data freshness.",
        "ob2t": "A→B routing built for bikes", "ob2d": "“City” and “MTB” profiles, elevation gain and share of the ride on infrastructure.",
        "ob3t": "We keep the map fresh together", "ob3d": "Report problems and add lanes — earn points for accepted contributions.",
        "signSub": "Moscow's cycling map, kept fresh by the community", "signApple": "Sign in with Apple", "signGoogle": "Sign in with Google",
        "signNote": "Sign-in is required. We store only your sign-in id, nickname and contributions.",
        "guestEnter": "Continue without sign-in",
        "editProfile": "Edit profile", "save": "Save", "nickname": "Nickname",
        "editSegment": "Edit", "segRemoved": "No longer exists", "editSuccess": "Submitted for review",
        "searchPh": "Search place or address",
        "actionTitle": "What would you like to add?",
        "aReport": "Report a problem", "aDraw": "Suggest a bike lane", "aPoi": "Add a place (POI)",
        "tMap": "Map", "tRoute": "Route", "tContrib": "My impact", "tProfile": "Profile", "tHome": "Home", "tQuests": "League",
        "kind_prot": "Protected bike path", "kind_lane": "Painted lane on road", "kind_shared": "Shared with pedestrians", "kind_mtb": "MTB trail", "kind_other": "Bike route",
        "surf_asphalt": "Asphalt", "surf_ground": "Ground", "surf_gravel": "Gravel", "surf_unknown": "Unknown",
        "poi_workshop": "Repair shop", "poi_parking": "Bike parking", "poi_rental": "Bike rental", "poi_fountain": "Drinking fountain",
        "cat_pothole": "Pothole", "cat_glass": "Glass / debris", "cat_closure": "Road closure", "cat_hazard": "Hazard", "cat_other": "Other",
        "surface": "Surface", "quality": "Condition", "source": "Source", "updated": "Updated",
        "srcOsm": "OpenStreetMap", "srcCom": "Community data", "good": "Good", "reportHere": "Report a problem",
        "address": "Address", "routeHere": "Route here",
        "confirm": "Confirm", "gone": "Gone now", "confN": "confirmations",
        "layersTitle": "Map layers", "legend": "Infrastructure types", "lInfra": "Cycling infrastructure", "lMtb": "MTB trails", "lPoi": "Useful places", "lReports": "Reports",
        "searchTitle": "Search", "recent": "Recent",
        "routeTitle": "Route", "from": "From", "to": "To", "myLoc": "My location", "pickOnMap": "Pick on map",
        "profCity": "City", "profMtb": "MTB", "build": "Build route", "rebuild": "Edit", "dist": "Distance", "timeL": "Time", "ascent": "Ascent",
        "onInfra": "on cycling infrastructure", "elevation": "Elevation profile", "saveRoute": "Save to favorites", "savedRoute": "Route saved",
        "routeHintTitle": "Where to?", "routeHintDesc": "Pick a point on the map, search an address, or start from your location.",
        "contribTitle": "My impact", "lvl": "Level", "toNext": "to level", "xpEdits": "edits", "xpReports": "reports", "xpConf": "confirms",
        "history": "Points history", "rankTop": "Top 3% of district riders",
        "today": "today", "yst": "yesterday",
        "profileTitle": "Profile", "favorites": "Favorites", "myReports": "My reports", "myEdits": "My edits", "ridesItem": "Rides", "settingsItem": "Settings", "pts": "points",
        "ridesTitle": "Rides", "healthTitle": "Import from Apple Health", "healthWhy": "We read cycling workouts to show track, speed and heart rate. Data stays only on your device and is never sent to the server.", "healthConnect": "Allow Health access", "healthPriv": "Read-only · Local",
        "importSel": "Import", "avgSpeed": "Avg", "maxSpeed": "Max", "durationL": "Time", "heartL": "Avg HR", "localOnly": "Stored on device only",
        "ridesEmpty": "No cycling workouts found", "ridesEmptyHint": "Record a ride in your health app or watch — it will show up here.", "healthUnavailable": "Apple Health isn't available in this environment",
        "settingsTitle": "Settings", "language": "Language", "theme": "Appearance", "themeLight": "Light", "themeDark": "Dark", "themeSystem": "System", "about": "About", "privacyItem": "Privacy policy", "rulesItem": "Community rules", "deleteAcc": "Delete account", "versionL": "Version", "deleteWarn": "Your edits and reports stay on the map but are unlinked from you.", "deleteConfirm": "Delete account?",
        "repTitle": "Problem on the map", "chooseCat": "What happened?", "commentL": "Comment", "commentPh": "Describe in more detail (optional)", "photosL": "Photos · up to 3", "locationL": "Location — from your position", "submit": "Submit", "repSuccess": "Thanks! +10 points after review",
        "drawTitle": "New bike lane", "drawHint": "Tap the map to place points of the line", "drawHint2": "Drag points to fine-tune", "ptsN": "points", "undo": "Undo", "clearL": "Clear", "drawNext": "Next", "drawBack": "Back", "drawKindL": "Lane type", "drawSurfaceL": "Surface", "drawPhotoL": "Photo (optional)", "drawSubmit": "Submit for review", "drawSuccess": "Lane submitted! +50 points after review", "reviewNote": "Appears as “community data” after review",
        "poiAddTitle": "New place", "poiNameL": "Name", "poiNamePh": "e.g. “Repair shop”", "poiTypeL": "Place type", "poiSuccess": "Place submitted! +20 points after review",
        "hubHi": "Hi", "hubSub": "Ready to make the city better for bikes?",
        "xpTo": "XP to lvl", "streak": "day streak", "streakLabel": "Streak", "streakRecord": "best",
        "dailyQuests": "Daily quests", "questRefresh": "refresh in 6 h",
        "badgesL": "Badges", "leaderboard": "District leaderboard", "you": "You", "viewAll": "All",
        "qaReport": "Report", "qaLane": "Lane",
        "lvlUp": "Level up!", "levelUpOverline": "LEVEL UP!", "claim": "Claim", "questReady": "Ready to claim", "newBadge": "New badge",
        "locked": "Soon", "earnedL": "Earned", "progressL": "Progress",
        "leagueTitle": "League", "leaguePromo": "PROMOTION ZONE", "leagueDemo": "Below — relegation zone", "leaguePromoNote": "Top 5 advance to the next league", "seasonTier": "Tier", "daysShort": "d", "timeLeft": "left",
        "reason_edit_approved": "Edit approved", "reason_poi_approved": "Place approved", "reason_report_validated": "Report validated", "reason_confirm": "Report confirmation", "reason_quest": "Quest reward",
        "conquerNote": "3 lanes to conquer the district", "districtData": "District data", "districtFresh": "updated 2 days ago",
        "osmAttribution": "© OpenStreetMap contributors", "odblNote": "Map data © OpenStreetMap contributors, ODbL licensed.", "routesAdvisory": "Routes are advisory. Always judge actual road conditions yourself.", "aboutTagline": "A fresh cycling-infrastructure map, kept in shape by the community.",
        "rulesTitle": "Community rules", "rule1t": "Verify on the ground", "rule1d": "Add lanes and places you're sure about — from reality, not memory.", "rule2t": "Respect privacy", "rule2d": "Avoid creating reports right at your home if you don't want to reveal your location.", "rule3t": "Be precise", "rule3d": "Accurate type and surface help others plan a safe route.", "rule4t": "No spam", "rule4d": "Duplicates and false edits are rejected in moderation and earn no points.",
        "loading": "Loading…", "retry": "Retry", "netError": "Couldn't load. Check your connection.",
    ]
}
